	drop table if exists `tb1002`;
	create table `tb1002`( 
  			`code`        varchar(60) comment '竞赛编号' ,
  			`name`        varchar(60) comment '名称' ,
  			`start_time`       datetime comment '竞赛开始时间' ,
  			`end_time`       datetime comment '竞赛结束时间' ,
  			`enroll_start_time`       datetime comment '报名开始时间' ,
  			`enroll_end_time`       datetime comment '报名结束时间' ,
  			`address`        varchar(60) comment '地址' ,
  			`status`        varchar(6) comment '状态' ,
  			`all_num`       int comment '竞赛总人数' ,
  			`enroll_num`       int comment '报名人数' ,
  			`contact_mobile`        varchar(60) comment '联系人电话' ,
  			`reward_num`       int comment '奖金总人数' ,
  			`reward_amount`       decimal(10,2) comment '奖金总金额' ,
  			`sreward_memberno`        varchar(60) comment '特等奖人员微信号' ,
  			`sreward_amount`       decimal(10,2) comment '特等奖金额' ,
  			`contact_name`        varchar(60) comment '比赛联系人姓名' ,
  			`eqcoed_num`       int comment '二维码个数' ,
  			`note`        varchar(60) comment '备注' ,
  			`id`        varchar(60) comment '技术主键' ,
  			`version`       int comment '版本号' ,
  			`is_remove`        varchar(1) comment '是否删除' ,
  			`create_time`       datetime comment '记录创建时间' ,
  			`update_time`       datetime comment '记录修改时间' ,
  			`create_by`        varchar(60) comment '创建人' ,
  			`update_by`        varchar(60) comment '修改人' ,
  		primary key (`id`)
	 ) comment='比赛，竞赛';
